### ISSUE TITLE
why is the ivaultguardian.sol interface empty

### ISSUE THREAD

**Issue by moyinmaala** [Cyfrin/8-vault-guardians-audit#5]
i just finished lesson 1-7 and i wondering why  the interface **ivaultguardian.sol**  is empty and if its a mistake or  part of its functionality or a bug. please help

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

interface IVaultGuardians {}
```

**Comment by Equious** [comment]
I'm actually unsure here. 😅 @PatrickAlphaC maybe you could comment? Could have been something that was intended to be included but ultimately not filled out?

**Comment by PatrickAlphaC** [comment]
It was pretty much just something to make this audit more horrible. 

"Why is this shit blank?"

I should remove this section from the course...
